#!/usr/bin/python

import os
import sys
import pdb
import logging
import argparse
from itertools import *

from racepro import *

##############################################################################
def show_syscalls(args):
    session = Session(load_events(args.logfile))
    for proc in session.processes.itervalues():
        for sys in proc.syscalls:
            print('[%d][%3d] %s' %
                  (proc.pid, sys.syscall_index + 1, sys))
        print('')
    return 0

##############################################################################
def show_races(args):
    graph = ExecutionGraph(load_events(args.logfile))
    logging.debug('graph: %s' % networkx.convert.to_edgelist(graph))
    return find_show_races(graph, args)

##############################################################################
def show_toctou(args):
    graph = ExecutionGraph(load_events(args.logfile))
    logging.debug('graph: %s' % networkx.convert.to_edgelist(graph))
    return find_show_toctou(graph, args)

##########################################################################

parser_io = argparse.ArgumentParser(add_help=False)
parser_io.add_argument('logfile', metavar='INPUT',
                       help='File name of input log')
parser_io.add_argument('-o', '--output', dest='path', metavar='PREFIX',
                       help='Prefix for output files')

parser_races = argparse.ArgumentParser(add_help=False)
parser_races.add_argument('-c', '--count', dest='count',
                          metavar='COUNT', type=int, default=1000,
                          help='Limit results to COUNT races')
parser_races.add_argument('--no-exit-races', dest='no_exit_races',
                          action='store_true', default=False,
                          help='Do not detect exit-exit-wait race')
parser_races.add_argument('--no-signal-races', dest='no_signal_races',
                          action='store_true', default=False,
                          help='Do not detect signal race')

desc = 'Process and modify scribe execution log'
parser = argparse.ArgumentParser(description=desc)
parser.add_argument('-d', dest='debug',
                    action='store_true', default=False,
                    help='Increase debug vebosity')
parser.add_argument('-v', dest='verbose',
                    action='store_true', default=False,
                    help='Increase vebosity level')

subparsers = parser.add_subparsers(title='subcommands')

parser_show_syscalls = subparsers.add_parser(
    'show-syscalls', parents=[parser_io])
parser_show_syscalls.set_defaults(func=show_syscalls)

parser_show_races = subparsers.add_parser(
    'show-races', parents=[parser_io, parser_races])
parser_show_races.set_defaults(func=show_races)

parser_show_toctou = subparsers.add_parser(
    'show-toctou', parents=[parser_io])
parser_show_toctou.set_defaults(func=show_toctou)

args = parser.parse_args()

log = logging.ERROR
if args.verbose: log = logging.INFO
if args.debug: log = logging.DEBUG
logging.basicConfig(level=log, stream=sys.stdout)

if not args.path:
    args.path = os.path.splitext(args.logfile)[0]

ret = args.func(args)
exit(0 if ret >= 0 else -ret)
