#!/usr/bin/python

import os
import sys
import argparse
from racepro import *

desc = 'perform TOCTOU attack or show TOCTOU details'
parser = argparse.ArgumentParser(description = desc)

subparsers = parser.add_subparsers(title='action', dest='action')
parser_show = subparsers.add_parser('show', help='show TOCTOU details')
parser_show.add_argument('type', nargs='+', help='pattern name')

parser_attack = subparsers.add_parser('attack', help='perform attack')
parser_attack.add_argument('-f', '--file', dest='file', nargs="*",
                           help='pattern name and arguments in files')
parser_attack.add_argument('type', nargs='?', help='patern name')
parser_attack.add_argument('args', nargs='*', help='arguments for attacker')

args = vars(parser.parse_args())

if args['action'] == 'show':
    for t in args['type']:
        print '%s: ' % t
        explain_toctou (t)

if args['action'] == 'attack':
    if args['file'] is not None:
        for f in args['file']:
            for c in open(f, 'r').read().split('\n'):
                if len(c.strip()) == 0:
                    continue
                os.system('%s %s' % (sys.argv[0], c))

    if args['type'] is not None:
        attack_toctou (args['type'], args['args'])
