#!/usr/bin/python

import os
import sys
import argparse
from racepro import *

desc = 'perform TOCTOU attack or show TOCTOU details'
parser = argparse.ArgumentParser(description = desc)

subparsers = parser.add_subparsers(title='action', dest='action')
parser_show = subparsers.add_parser('explain', help='explain TOCTOU details')
parser_show.add_argument('type', nargs='+', help='pattern name')

parser_attack = subparsers.add_parser('attack', help='perform attack')
parser_attack.add_argument('type', help='patern name')
parser_attack.add_argument('args', nargs='*', help='arguments for attacker')

parser_attack = subparsers.add_parser('test', help='perform generic test')
parser_attack.add_argument('type', help='patern name')
parser_attack.add_argument('args', nargs='*', help='arguments for attacker')

args = vars(parser.parse_args())

if args['action'] == 'explain':
    for t in args['type']:
        print('%s: ' % t)
        print('    %s' % explain_toctou(t))

if args['action'] == 'attack':
    attack_toctou(args['type'], args['args'])

if args['action'] == 'test':
    test_toctou(args['type'], args['args'])


