#!/usr/bin/python

import sys
import execute

if len(sys.argv) < 2:
    print('Usage: ioslate CMD [ARGS...]')
    exit(1)

with execute.ExecuteJail() as jailed:
    jailed.execute(sys.argv[1:])

    
